apiVersion: apps/v1
kind: Deployment
metadata:
  name: barista
  namespace: coffeeshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: barista
  template:
    metadata:
      labels:
        app: barista
    spec:
      containers:
      - name: barista
        image: 522569276716.dkr.ecr.us-east-1.amazonaws.com/coffeeshop-barista:latest
        env:
        - name: APP_NAME
          value: "barista"
        - name: IN_DOCKER
          valueFrom:
            configMapKeyRef:
              name: coffeeshop-config
              key: IN_DOCKER
        - name: PG_URL
          valueFrom:
            secretKeyRef:
              name: coffeeshop-secrets
              key: PG_URL
        - name: PG_DSN_URL
          valueFrom:
            secretKeyRef:
              name: coffeeshop-secrets
              key: PG_DSN_URL
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@rabbitmq:5672/"
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: barista
  namespace: coffeeshop
spec:
  selector:
    app: barista
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP