apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter
  namespace: coffeeshop
spec:
  replicas: 1= 1
  selector:
    matchLabels:
      app: counter
  template:
    metadata:
      labels:
        app: counter
    spec:
      containers:
      - name: counter
        image: 522569276716.dkr.ecr.us-east-1.amazonaws.com/coffeeshop-counter:latest自主:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        ports:
        - containerPort: 5002
        env:
        - name: APP_NAME
          value: "counter"
        - name: IN_DOCKER
          valueFrom:
            configMapKeyRef:
              name: coffeeshop-config
              key: IN_DOCKER
        - name: PG_URL
          valueFrom:
            secretKeyRef:
              name: coffeeshop-secrets
              key: PG_URL
        - name: PG_DSN_URL
          valueFrom:
            secretKeyRef:
              name: coffeeshop-secrets
              key: PG_DSN_URL
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@rabbitmq:5672/"
        - name: PRODUCT_CLIENT_URL
          value: "product:5001"
        livenessProbe:
          httpGet:
            path: /health
            port: 5002
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5002
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: counter
  namespace: coffeeshop
spec:
  selector:
    app: counter
  ports:
  - port: 5002
    targetPort: 5002
  type: ClusterIP