apiVersion: secrets-store.csi.driver.k8s.io/v1
kind: SecretProviderClass
metadata:
  name: coffeeshop-secrets
  namespace: coffeeshop
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "coffeeshop-db-credentials"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: db-username
          - path: password
            objectAlias: db-password
          - path: host
            objectAlias: db-host
          - path: port
            objectAlias: db-port
          - path: dbname
            objectAlias: db-dbname