apiVersion: secrets-store.csi.driver.k8s.io/v1
kind: SecretProviderClass
metadata:
  name: test-secrets
  namespace: coffeeshop
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "coffeeshop-db-credentials"
        objectType: "secretsmanager"